Use python3 to run repo command to fix invalid syntax issue
  File ".repo/repo/repo", line 51
    def print(self, *args, **kwargs):
            ^
SyntaxError: invalid syntax

Change-Id: I37d679d1775e8fe3aaf8cb3c4d351a071bfd1456
(cherry picked from commit 34e697e3c689ee0b2539a97c9e35373759301d2a)